name: Release

on:
  push:
    tags:
      - '*'

env:
  NODE_VERSION: 16.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run prebuild
      - run: cp README.md LICENSE dist/config
      - run: npm publish
        working-directory: dist/config
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
